global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'football-api-monitor'

scrape_configs:
  # Football Standings API metrics
  - job_name: 'football-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['football-api:8080']
        labels:
          application: 'football-standings'
          environment: 'docker'
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
