server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: football-standings
  cache:
    type: simple

# External API Configuration
api:
  football:
    base-url: https://apiv3.apifootball.com/
    api-key: ${FOOTBALL_API_KEY:9bb66184e0c8145384fd2cc0f7b914ada57b4e8fd2e4d6d586adcc27c257a978}
    timeout: 10000

# Cache Configuration
cache:
  ttl:
    countries: 86400000  # 24 hours in milliseconds
    leagues: 3600000     # 1 hour
    teams: 3600000       # 1 hour
    standings: 300000    # 5 minutes

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,httptrace,threaddump,heapdump
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms,1s,2s,5s
  tracing:
    sampling:
      probability: 1.0

# Logging Configuration
logging:
  level:
    root: INFO
    com.sapient.football: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
