name: Full Stack CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

env:
  JAVA_VERSION: '21'
  NODE_VERSION: '18'

jobs:
  validate:
    name: Validate Monorepo
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check directory structure
      run: |
        echo "Checking repository structure..."
        ls -la
        echo ""
        echo "Backend files:"
        ls -la backend/ | head -10
        echo ""
        echo "Frontend files:"
        ls -la frontend/ | head -10
        
    - name: Validate Docker Compose
      run: |
        if [ -f "docker-compose.yml" ]; then
          echo "✅ docker-compose.yml found"
          docker compose config > /dev/null && echo "✅ docker-compose.yml is valid" || echo "❌ docker-compose.yml has errors"
        else
          echo "❌ docker-compose.yml not found"
        fi

  backend-build-test:
    name: Backend Build & Test
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Grant execute permission for gradlew
      run: chmod +x backend/gradlew
      
    - name: Build and Test
      working-directory: ./backend
      run: |
        ./gradlew clean build
        echo "✅ Backend build and tests passed"
        
    - name: Upload backend artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-jar
        path: backend/build/libs/*.jar
        retention-days: 1

  frontend-build-test:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install and Build
      working-directory: ./frontend
      run: |
        npm ci
        npm run build
        echo "✅ Frontend build passed"
      env:
        CI: false
        
    - name: TypeScript Check
      working-directory: ./frontend
      run: npx tsc --noEmit
      
    - name: Upload frontend artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/build/
        retention-days: 1

  newman-api-tests:
    name: Newman API Tests
    runs-on: ubuntu-latest
    needs: backend-build-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install Newman
      run: npm install -g newman newman-reporter-htmlextra
      
    - name: Dummy API Test (Backend not running)
      run: |
        echo "========================================="
        echo "🧪 NEWMAN API TESTS (DUMMY)"
        echo "========================================="
        echo ""
        echo "In a real CI/CD pipeline, this would:"
        echo "  1. Start backend service in Docker"
        echo "  2. Wait for health check"
        echo "  3. Run: newman run Football-Standings-API.postman_collection.json"
        echo "  4. Generate HTML report"
        echo ""
        if [ -f "Football-Standings-API.postman_collection.json" ]; then
          echo "✅ Postman collection found"
          echo "✅ Would run 13 test suites with 58 assertions"
        else
          echo "❌ Postman collection not found"
        fi
        echo ""
        echo "✅ Dummy API tests completed!"

  docker-compose-test:
    name: Docker Compose Integration Test
    runs-on: ubuntu-latest
    needs: [backend-build-test, frontend-build-test]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker images
      run: |
        echo "Building backend Docker image..."
        docker build -t football-backend:test ./backend
        echo "✅ Backend image built"
        
        echo "Building frontend Docker image..."
        docker build -t football-frontend:test ./frontend
        echo "✅ Frontend image built"
        
    - name: Dummy Docker Compose Test
      run: |
        echo "========================================="
        echo "🐳 DOCKER COMPOSE INTEGRATION TEST"
        echo "========================================="
        echo ""
        echo "In a real test, this would:"
        echo "  1. Start services: docker compose up -d"
        echo "  2. Wait for services to be healthy"
        echo "  3. Test backend: curl http://localhost:8080/api/health"
        echo "  4. Test frontend: curl http://localhost:3000"
        echo "  5. Test integration: Frontend -> Backend API calls"
        echo "  6. Cleanup: docker compose down"
        echo ""
        echo "✅ Integration test completed!"

  deploy-staging-dummy:
    name: Deploy to Staging (Dummy)
    runs-on: ubuntu-latest
    needs: [backend-build-test, frontend-build-test, newman-api-tests]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: staging
      url: https://staging.football-app.com
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      
    - name: Deploy Backend to Staging
      run: |
        echo "========================================="
        echo "🚀 DEPLOY BACKEND TO STAGING"
        echo "========================================="
        echo ""
        echo "Deployment target: AWS ECS Staging"
        echo "Cluster: football-staging-cluster"
        echo "Service: backend-staging"
        echo ""
        echo "Steps that would execute:"
        echo "  1. Push image to ECR"
        echo "  2. Update ECS task definition"
        echo "  3. Force new deployment"
        echo "  4. Wait for service stability"
        echo ""
        echo "✅ Backend deployed to staging!"
        
    - name: Deploy Frontend to Staging
      run: |
        echo "========================================="
        echo "🚀 DEPLOY FRONTEND TO STAGING"
        echo "========================================="
        echo ""
        echo "Deployment target: AWS S3 + CloudFront"
        echo "Bucket: football-staging-bucket"
        echo "Distribution: E123456789STAGING"
        echo ""
        echo "Steps that would execute:"
        echo "  1. Sync files to S3"
        echo "  2. Invalidate CloudFront cache"
        echo "  3. Verify deployment"
        echo ""
        echo "✅ Frontend deployed to staging!"
        
    - name: Smoke Tests
      run: |
        echo "========================================="
        echo "💨 SMOKE TESTS"
        echo "========================================="
        echo ""
        echo "Testing endpoints:"
        echo "  ✅ https://staging.football-app.com - HTTP 200"
        echo "  ✅ https://api-staging.football-app.com/health - HTTP 200"
        echo "  ✅ https://api-staging.football-app.com/api/countries - HTTP 200"
        echo ""
        echo "✅ All smoke tests passed!"

  deploy-production-dummy:
    name: Deploy to Production (Dummy)
    runs-on: ubuntu-latest
    needs: deploy-staging-dummy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://football-app.com
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      
    - name: Pre-deployment Checks
      run: |
        echo "========================================="
        echo "🔍 PRE-DEPLOYMENT CHECKS"
        echo "========================================="
        echo ""
        echo "✅ Staging tests passed"
        echo "✅ Smoke tests passed"
        echo "✅ No critical issues in logs"
        echo "✅ Database migrations ready"
        echo ""
        echo "Ready for production deployment!"
        
    - name: Deploy Backend to Production
      run: |
        echo "========================================="
        echo "🚀 DEPLOY BACKEND TO PRODUCTION"
        echo "========================================="
        echo ""
        echo "Deployment strategy: Blue-Green"
        echo "Target: AWS ECS Production"
        echo "Cluster: football-prod-cluster"
        echo "Service: backend-prod"
        echo ""
        echo "Steps that would execute:"
        echo "  1. Create new task definition"
        echo "  2. Deploy to blue environment"
        echo "  3. Run health checks"
        echo "  4. Switch traffic to blue"
        echo "  5. Monitor for 5 minutes"
        echo "  6. Decommission green (old) environment"
        echo ""
        echo "✅ Backend deployed to production!"
        
    - name: Deploy Frontend to Production
      run: |
        echo "========================================="
        echo "🚀 DEPLOY FRONTEND TO PRODUCTION"
        echo "========================================="
        echo ""
        echo "Deployment target: AWS S3 + CloudFront"
        echo "Bucket: football-prod-bucket"
        echo "Distribution: E123456789PROD"
        echo ""
        echo "Steps that would execute:"
        echo "  1. Backup current version"
        echo "  2. Sync new files to S3"
        echo "  3. Invalidate CloudFront cache"
        echo "  4. Verify deployment"
        echo "  5. Update DNS if needed"
        echo ""
        echo "✅ Frontend deployed to production!"
        
    - name: Post-Deployment Verification
      run: |
        echo "========================================="
        echo "✅ POST-DEPLOYMENT VERIFICATION"
        echo "========================================="
        echo ""
        echo "Health Checks:"
        echo "  ✅ https://football-app.com - HTTP 200"
        echo "  ✅ https://api.football-app.com/health - HTTP 200"
        echo "  ✅ https://api.football-app.com/actuator/health - HTTP 200"
        echo ""
        echo "Functional Tests:"
        echo "  ✅ Country dropdown loads data"
        echo "  ✅ League selection works"
        echo "  ✅ Standings display correctly"
        echo ""
        echo "Performance Metrics:"
        echo "  ✅ Response time < 500ms"
        echo "  ✅ Error rate < 0.1%"
        echo "  ✅ CPU usage < 70%"
        echo "  ✅ Memory usage < 80%"
        echo ""
        echo "✅ All verification checks passed!"
        
    - name: Notification
      run: |
        echo "========================================="
        echo "📢 DEPLOYMENT NOTIFICATION"
        echo "========================================="
        echo ""
        echo "🎉 Production deployment completed successfully!"
        echo ""
        echo "Details:"
        echo "  • Environment: Production"
        echo "  • Commit: ${{ github.sha }}"
        echo "  • Author: ${{ github.actor }}"
        echo "  • Time: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        echo ""
        echo "URLs:"
        echo "  • Application: https://football-app.com"
        echo "  • API: https://api.football-app.com"
        echo "  • Monitoring: https://grafana.football-app.com"
        echo ""
        echo "In production, would send notifications to:"
        echo "  • Slack: #deployments channel"
        echo "  • Email: team@football-app.com"
        echo "  • PagerDuty: Deployment event"

  rollback-plan:
    name: Rollback Plan (Documentation)
    runs-on: ubuntu-latest
    needs: deploy-production-dummy
    if: failure()
    
    steps:
    - name: Rollback Instructions
      run: |
        echo "========================================="
        echo "⚠️  ROLLBACK INSTRUCTIONS"
        echo "========================================="
        echo ""
        echo "If deployment fails, execute rollback:"
        echo ""
        echo "Backend Rollback:"
        echo "  aws ecs update-service \\"
        echo "    --cluster football-prod-cluster \\"
        echo "    --service backend-prod \\"
        echo "    --task-definition backend-prod:PREVIOUS_VERSION"
        echo ""
        echo "Frontend Rollback:"
        echo "  aws s3 sync s3://football-prod-backup/previous/ s3://football-prod-bucket/ --delete"
        echo "  aws cloudfront create-invalidation --distribution-id E123456789PROD --paths '/*'"
        echo ""
        echo "Manual rollback trigger:"
        echo "  gh workflow run rollback.yml --ref main"
